{
  "name": "BIMGuardAnalytics",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-GB",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "issues",
        "description": "Fact table. One row per BIMGUARD AI compliance issue. GC-001 and CC-001 outputs.",
        "columns": [
          { "name": "IssueID",            "dataType": "string",  "sourceColumn": "IssueID" },
          { "name": "ProjectID",           "dataType": "string",  "sourceColumn": "ProjectID" },
          { "name": "ModelID",             "dataType": "string",  "sourceColumn": "ModelID" },
          { "name": "RuleID",              "dataType": "string",  "sourceColumn": "RuleID" },
          { "name": "LocationID",          "dataType": "string",  "sourceColumn": "LocationID" },
          { "name": "AssigneeID",          "dataType": "string",  "sourceColumn": "AssigneeID" },
          { "name": "SeverityID",          "dataType": "string",  "sourceColumn": "SeverityID" },
          { "name": "StatusID",            "dataType": "string",  "sourceColumn": "StatusID" },
          { "name": "IssueTypeID",         "dataType": "string",  "sourceColumn": "IssueTypeID" },
          { "name": "IFCGUID",             "dataType": "string",  "sourceColumn": "IFCGUID" },
          { "name": "BCFGuid",             "dataType": "string",  "sourceColumn": "BCFGuid" },
          { "name": "ElementID",           "dataType": "string",  "sourceColumn": "ElementID" },
          { "name": "ElementType",         "dataType": "string",  "sourceColumn": "ElementType" },
          { "name": "MaterialPrimary",     "dataType": "string",  "sourceColumn": "MaterialPrimary" },
          { "name": "MaterialSecondary",   "dataType": "string",  "sourceColumn": "MaterialSecondary" },
          { "name": "JointType",           "dataType": "string",  "sourceColumn": "JointType" },
          { "name": "EnvironmentClass",    "dataType": "string",  "sourceColumn": "EnvironmentClass" },
          { "name": "SystemType",          "dataType": "string",  "sourceColumn": "SystemType" },
          { "name": "GalvanicScore",       "dataType": "double",  "sourceColumn": "GalvanicScore" },
          { "name": "CreviceScore",        "dataType": "double",  "sourceColumn": "CreviceScore" },
          { "name": "CombinedScore",       "dataType": "double",  "sourceColumn": "CombinedScore" },
          { "name": "DominantMechanism",   "dataType": "string",  "sourceColumn": "DominantMechanism" },
          { "name": "X",                   "dataType": "double",  "sourceColumn": "X" },
          { "name": "Y",                   "dataType": "double",  "sourceColumn": "Y" },
          { "name": "Z",                   "dataType": "double",  "sourceColumn": "Z" },
          { "name": "CostImpactGBP",       "dataType": "double",  "sourceColumn": "CostImpactGBP",
            "formatString": "£#,##0.00" },
          { "name": "DelayDays",           "dataType": "int64",   "sourceColumn": "DelayDays" },
          { "name": "Mitigation",          "dataType": "string",  "sourceColumn": "Mitigation" },
          { "name": "Notes",               "dataType": "string",  "sourceColumn": "Notes" },
          { "name": "CreatedDate",         "dataType": "dateTime","sourceColumn": "CreatedDate",
            "formatString": "dd/MM/yyyy",
            "annotations": [{ "name": "UnderlyingDateTimeDataType", "value": "Date" }] },
          { "name": "ClosedDate",          "dataType": "dateTime","sourceColumn": "ClosedDate",
            "formatString": "dd/MM/yyyy" },
          { "name": "RunID",               "dataType": "string",  "sourceColumn": "RunID" },
          { "name": "IsOpen",              "dataType": "boolean", "sourceColumn": "IsOpen" },
          { "name": "IsCriticalOrHigh",    "dataType": "boolean", "sourceColumn": "IsCriticalOrHigh" },
          { "name": "IsComplianceFailure", "dataType": "boolean", "sourceColumn": "IsComplianceFailure" }
        ],
        "measures": [
          {
            "name": "Total Issues",
            "expression": "COUNTROWS(issues)",
            "description": "Total number of compliance issues."
          },
          {
            "name": "Open Issues",
            "expression": "CALCULATE(COUNTROWS(issues), issues[IsOpen] = TRUE())",
            "description": "Issues with status Open, In Progress, or In Review."
          },
          {
            "name": "Critical Issues",
            "expression": "CALCULATE(COUNTROWS(issues), issues[SeverityID] = \"SEV-CRIT\")"
          },
          {
            "name": "High Issues",
            "expression": "CALCULATE(COUNTROWS(issues), issues[SeverityID] = \"SEV-HIGH\")"
          },
          {
            "name": "Medium Issues",
            "expression": "CALCULATE(COUNTROWS(issues), issues[SeverityID] = \"SEV-MED\")"
          },
          {
            "name": "Low Issues",
            "expression": "CALCULATE(COUNTROWS(issues), issues[SeverityID] = \"SEV-LOW\")"
          },
          {
            "name": "Critical or High Issues",
            "expression": "CALCULATE(COUNTROWS(issues), issues[IsCriticalOrHigh] = TRUE())"
          },
          {
            "name": "Closed Issues",
            "expression": "CALCULATE(COUNTROWS(issues), issues[StatusID] = \"STS-CLOS\")"
          },
          {
            "name": "Approved Issues",
            "expression": "CALCULATE(COUNTROWS(issues), issues[StatusID] = \"STS-APPR\")"
          },
          {
            "name": "Compliance Failures",
            "expression": "CALCULATE(COUNTROWS(issues), issues[IsComplianceFailure] = TRUE())",
            "description": "Issues with CombinedScore >= 0.35 (Medium risk or above)."
          },
          {
            "name": "Compliance Score %",
            "expression": "VAR TotalIssues = COUNTROWS(issues)\nVAR Failures = [Compliance Failures]\nRETURN IF(TotalIssues = 0, BLANK(), 1 - DIVIDE(Failures, TotalIssues, 0))",
            "formatString": "0.0%",
            "description": "Proportion of elements that passed compliance (score < 0.35)."
          },
          {
            "name": "Resolution Rate %",
            "expression": "DIVIDE([Closed Issues] + [Approved Issues], [Total Issues], 0)",
            "formatString": "0.0%"
          },
          {
            "name": "Total Cost Impact GBP",
            "expression": "SUM(issues[CostImpactGBP])",
            "formatString": "£#,##0",
            "description": "Total estimated remediation cost across all issues in context."
          },
          {
            "name": "Total Delay Days",
            "expression": "SUM(issues[DelayDays])",
            "description": "Total programme delay in working days."
          },
          {
            "name": "Avg Risk Score",
            "expression": "AVERAGE(issues[CombinedScore])",
            "formatString": "0.000"
          },
          {
            "name": "Avg Galvanic Score",
            "expression": "AVERAGE(issues[GalvanicScore])",
            "formatString": "0.000"
          },
          {
            "name": "Avg Crevice Score",
            "expression": "AVERAGE(issues[CreviceScore])",
            "formatString": "0.000"
          },
          {
            "name": "Overdue Issues",
            "expression": "CALCULATE(\n    COUNTROWS(issues),\n    issues[IsOpen] = TRUE(),\n    DATEDIFF(issues[CreatedDate], TODAY(), DAY) > 30\n)",
            "description": "Open issues created more than 30 days ago."
          },
          {
            "name": "Avg Issue Age Days",
            "expression": "AVERAGEX(\n    FILTER(issues, issues[IsOpen] = TRUE()),\n    DATEDIFF(issues[CreatedDate], TODAY(), DAY)\n)",
            "formatString": "0",
            "description": "Average age in days for currently open issues."
          },
          {
            "name": "Issues This Month",
            "expression": "CALCULATE(\n    [Total Issues],\n    DATESMTD(DimDate[Date])\n)"
          },
          {
            "name": "Issues Previous Month",
            "expression": "CALCULATE(\n    [Total Issues],\n    PREVIOUSMONTH(DimDate[Date])\n)"
          },
          {
            "name": "Issues MoM Change",
            "expression": "[Issues This Month] - [Issues Previous Month]"
          },
          {
            "name": "Issues MoM Change %",
            "expression": "DIVIDE([Issues MoM Change], [Issues Previous Month], 0)",
            "formatString": "+0.0%;-0.0%;0.0%"
          },
          {
            "name": "Unassigned Issues",
            "expression": "CALCULATE(COUNTROWS(issues), issues[AssigneeID] = \"ASN-UNASSIGNED\")"
          },
          {
            "name": "Assigned Issues",
            "expression": "CALCULATE(COUNTROWS(issues), issues[AssigneeID] <> \"ASN-UNASSIGNED\")"
          },
          {
            "name": "Assigned Rate %",
            "expression": "DIVIDE([Assigned Issues], [Total Issues], 0)",
            "formatString": "0.0%"
          },
          {
            "name": "Galvanic Issues",
            "expression": "CALCULATE(COUNTROWS(issues), issues[DominantMechanism] = \"Galvanic\")"
          },
          {
            "name": "Crevice Issues",
            "expression": "CALCULATE(COUNTROWS(issues), issues[DominantMechanism] = \"Crevice\")"
          },
          {
            "name": "Failure Rate %",
            "expression": "DIVIDE([Compliance Failures], [Total Issues], 0)",
            "formatString": "0.0%"
          }
        ],
        "partitions": [
          {
            "name": "issues-partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(DataFolderPath & \"facts/issues.csv\"), [Delimiter=\",\", Columns=35, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"GalvanicScore\", type number}, {\"CreviceScore\", type number}, {\"CombinedScore\", type number},",
                "        {\"X\", type number}, {\"Y\", type number}, {\"Z\", type number},",
                "        {\"CostImpactGBP\", type number}, {\"DelayDays\", Int64.Type},",
                "        {\"CreatedDate\", type date}, {\"ClosedDate\", type date},",
                "        {\"IsOpen\", type logical}, {\"IsCriticalOrHigh\", type logical}, {\"IsComplianceFailure\", type logical}",
                "    })",
                "in",
                "    ChangedTypes"
              ]
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "description": "Date dimension — mark as Date Table on the Date column.",
        "columns": [
          { "name": "Date",        "dataType": "dateTime", "sourceColumn": "Date",
            "formatString": "dd/MM/yyyy",
            "annotations": [{ "name": "UnderlyingDateTimeDataType", "value": "Date" }] },
          { "name": "Year",        "dataType": "int64",   "sourceColumn": "Year" },
          { "name": "Quarter",     "dataType": "string",  "sourceColumn": "Quarter" },
          { "name": "Month",       "dataType": "int64",   "sourceColumn": "Month" },
          { "name": "MonthName",   "dataType": "string",  "sourceColumn": "MonthName" },
          { "name": "Week",        "dataType": "int64",   "sourceColumn": "Week" },
          { "name": "Day",         "dataType": "int64",   "sourceColumn": "Day" },
          { "name": "DayName",     "dataType": "string",  "sourceColumn": "DayName" },
          { "name": "IsWeekend",   "dataType": "boolean", "sourceColumn": "IsWeekend" },
          { "name": "YearMonth",   "dataType": "string",  "sourceColumn": "YearMonth" }
        ],
        "isHidden": false,
        "annotations": [
          { "name": "__PBI_MarkAsDateTable_IslandId", "value": "Date" }
        ],
        "partitions": [
          {
            "name": "DimDate-partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    StartDate = #date(2024, 1, 1),",
                "    EndDate   = Date.From(DateTime.LocalNow()) + #duration(365, 0, 0, 0),",
                "    DateList  = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1,0,0,0)),",
                "    AsTable   = Table.FromList(DateList, Splitter.SplitByNothing(), {\"Date\"}, null, ExtraValues.Error),",
                "    AddYear   = Table.AddColumn(AsTable,    \"Year\",      each Date.Year([Date]),             Int64.Type),",
                "    AddQtr    = Table.AddColumn(AddYear,    \"Quarter\",   each \"Q\" & Text.From(Date.QuarterOfYear([Date])), type text),",
                "    AddMonth  = Table.AddColumn(AddQtr,     \"Month\",     each Date.Month([Date]),            Int64.Type),",
                "    AddMName  = Table.AddColumn(AddMonth,   \"MonthName\", each Date.MonthName([Date]),        type text),",
                "    AddWeek   = Table.AddColumn(AddMName,   \"Week\",      each Date.WeekOfYear([Date]),       Int64.Type),",
                "    AddDay    = Table.AddColumn(AddWeek,    \"Day\",       each Date.Day([Date]),              Int64.Type),",
                "    AddDName  = Table.AddColumn(AddDay,     \"DayName\",   each Date.DayOfWeekName([Date]),    type text),",
                "    AddWknd   = Table.AddColumn(AddDName,   \"IsWeekend\", each Date.DayOfWeek([Date]) >= 5,   type logical),",
                "    AddYM     = Table.AddColumn(AddWknd,    \"YearMonth\", each Text.From(Date.Year([Date])) & \"-\" & Text.PadStart(Text.From(Date.Month([Date])), 2, \"0\"), type text),",
                "    SetType   = Table.TransformColumnTypes(AddYM, {{\"Date\", type date}})",
                "in",
                "    SetType"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "issues_to_dim_severity",
        "fromTable": "issues", "fromColumn": "SeverityID",
        "toTable": "dim_severity", "toColumn": "SeverityID",
        "crossFilteringBehavior": "singleDirection"
      },
      {
        "name": "issues_to_dim_status",
        "fromTable": "issues", "fromColumn": "StatusID",
        "toTable": "dim_status", "toColumn": "StatusID",
        "crossFilteringBehavior": "singleDirection"
      },
      {
        "name": "issues_to_dim_rules",
        "fromTable": "issues", "fromColumn": "RuleID",
        "toTable": "dim_rules", "toColumn": "RuleID",
        "crossFilteringBehavior": "singleDirection"
      },
      {
        "name": "issues_to_dim_locations",
        "fromTable": "issues", "fromColumn": "LocationID",
        "toTable": "dim_locations", "toColumn": "LocationID",
        "crossFilteringBehavior": "singleDirection"
      },
      {
        "name": "issues_to_dim_assignments",
        "fromTable": "issues", "fromColumn": "AssigneeID",
        "toTable": "dim_assignments", "toColumn": "AssigneeID",
        "crossFilteringBehavior": "singleDirection"
      },
      {
        "name": "issues_to_dim_models",
        "fromTable": "issues", "fromColumn": "ModelID",
        "toTable": "dim_models", "toColumn": "ModelID",
        "crossFilteringBehavior": "singleDirection"
      },
      {
        "name": "issues_to_dim_projects",
        "fromTable": "issues", "fromColumn": "ProjectID",
        "toTable": "dim_projects", "toColumn": "ProjectID",
        "crossFilteringBehavior": "singleDirection"
      },
      {
        "name": "issues_to_dim_issue_types",
        "fromTable": "issues", "fromColumn": "IssueTypeID",
        "toTable": "dim_issue_types", "toColumn": "IssueTypeID",
        "crossFilteringBehavior": "singleDirection"
      },
      {
        "name": "issues_to_DimDate",
        "fromTable": "issues", "fromColumn": "CreatedDate",
        "toTable": "DimDate", "toColumn": "Date",
        "crossFilteringBehavior": "singleDirection"
      },
      {
        "name": "issue_status_history_to_issues",
        "fromTable": "issue_status_history", "fromColumn": "IssueID",
        "toTable": "issues", "toColumn": "IssueID",
        "crossFilteringBehavior": "singleDirection"
      }
    ],
    "expressions": [
      {
        "name": "DataFolderPath",
        "kind": "m",
        "expression": "\"C:/bimguard-analytics/analytics_export/\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "description": "Path to the analytics_export/ folder produced by analytics_export.py. Update this to point at your local output folder."
      }
    ]
  }
}
